name: Deploy
on:
    push:
        branches:
            - main
    # tags:
    # pull_request:
env:
    CARGO_TERM_COLOR: always

    # if a test fails, shows the backtrace
    RUST_BACKTRACE: 1

    # if depending on a ssh crate, use the git cli.
    CARGO_NET_GIT_FETCH_WITH_CLI: true
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - uses: actions/checkout@v4

            # rust compiler for creating binaries
            - name: Install latest nightly (for wasm)
              uses: dtolnay/rust-toolchain@nightly
              with:
                  targets: wasm32-unknown-unknown
                  components: rustfmt, clippy

            - name: Install Wasm Target
              run: |
                  set -e
                  rustup target add wasm32-unknown-unknown

            # Runs some Rust-related caching
            - uses: Swatinem/rust-cache@v2

            - name: Download wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Build Release wasm for Mamba1
              run: wasm-pack build --release --target web --out-dir "frontend/mamba1/pkg" --no-opt --no-default-features --features "ndarray,yew,mamba1"

            - name: Build Release wasm for Mamba2
              run: wasm-pack build --release --target web --out-dir "frontend/mamba2/pkg" --no-opt --no-default-features --features "ndarray,yew,mamba2"

            - name: Prepare Wasm Deploy
              run: |
                  set -e
                  # Prepare the publishing structure
                  mkdir -p publish/{mamba1,mamba2}

                  # move assets
                  mv frontend/mamba1/index.html publish/mamba1/
                  mv frontend/mamba2/index.html publish/mamba2/
                  mv frontend/mamba1/index.js publish/mamba1/
                  mv frontend/mamba2/index.js publish/mamba2/
                  mv frontend/mamba1/pkg/ publish/mamba1/pkg/
                  mv frontend/mamba2/pkg/ publish/mamba2/pkg/

                  # rm gitignore
                  rm publish/mamba1/pkg/.gitignore
                  rm publish/mamba2/pkg/.gitignore

            # Publish
            - name: Frontend Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./publish
                  keep_files: false
